# Generated by Django 2.1.8 on 2019-05-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190530_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(through='crm.CampaignContact', to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='campaigncontact',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Campaign'),
        ),
    ]
