# Created by Maximillian M. Estrada on 30-May-2019

version: "3.1"

services:
  # dengun_crm app service
  app: &app
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./src/dengun_crm:/dengun_crm
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - celery_worker
  # rabbitmq service
  rabbitmq:
      image: rabbitmq:3.7-alpine
  # celery worker service
  celery_worker:
    <<: *app
    command: sh -c "celery -A dengun_crm worker --loglevel=info"
    ports: []
    depends_on:
      - rabbitmq
